import { Toaster } from "@/components/ui/toaster";
import { ArweaveWalletKit } from "arweave-wallet-kit";
import "./globals.css";
// import {ArConnectStrategy} from "arweave-wallet-kit/dist/strategy/strategies/ArConnect";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ArweaveWalletKit config={{
          permissions:['ACCESS_ADDRESS','ACCESS_ALL_ADDRESSES', 'SIGN_TRANSACTION', 'DISPATCH'],
          ensurePermissions: true,
          // strategies:[new ArConnectStrategy()]
        }} >
          <main>{children}</main>
          <Toaster />
        </ArweaveWalletKit>
      </body>
    </html>
  );
}
